In [79]:
import pandas as pd
import numpy as np

In [80]:
df = pd.read_csv('letter.csv')
df

       T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   .. ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 17 columns]

In [81]:
df.isna().sum()

T      0
2      0
8      0
3      0
5      0
1      0
8.1    0
13     0
0      0
6      0
6.1    0
10     0
8.2    0
0.1    0
8.3    0
0.2    0
8.4    0
dtype: int64

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   T       19999 non-null  object
 1   2       19999 non-null  int64
 2   8       19999 non-null  int64
 3   3       19999 non-null  int64
 4   5       19999 non-null  int64
 5   1       19999 non-null  int64
 6   8.1     19999 non-null  int64
 7   13      19999 non-null  int64
 8   0       19999 non-null  int64
 9   6       19999 non-null  int64
 10  6.1     19999 non-null  int64
 11  10      19999 non-null  int64
 12  8.2     19999 non-null  int64
 13  0.1     19999 non-null  int64
 14  8.3     19999 non-null  int64
 15  0.2     19999 non-null  int64
 16  8.4     19999 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [83]:
df.describe()

,2,8,3,5,1,8.1,13,0,6,6.1,10,8.2,0.1,8.3,0.2,8.4
count,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.00000
mean,4.023651,7.035452,5.121956,5.372469,3.505975,6.897545,7.500175,4.628831,5.178609,8.282164,6.453823,7.928996,3.046252,8.338867,3.691935,7.80119
std,1.913206,3.304631,2.014568,2.261445,2.190441,2.026071,2.325087,2.699837,2.380875,2.488485,2.631016,2.080671,2.332500,1.546759,2.567004,1.61751
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.000000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.000000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.000000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.000000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.000000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.000000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000

In [84]:
df.shape

(19999, 17)

In [85]:
df.columns

Index(['T', '2', '8', '3', '5', '1', '8.1', '13', '0', '6', '6.1', '10', '8.2',
       '0.1', '8.3', '0.2', '8.4'],
      dtype='object')

In [86]:
x = df.drop(columns=['T'])
y = df['T']

In [87]:
from sklearn.preprocessing import LabelEncoder , StandardScaler

In [88]:
encoder_labels = LabelEncoder()
encoded_y = encoder_labels.fit_transform(y)

In [89]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [90]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train, y_test = train_test_split(x_scaled, encoded_y, random_state =42,test_size =0.2)

In [91]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential(
    [
        Dense(128, input_dim = x_train.shape[1], activation='relu'),
        Dense(64,activation='relu'),
        Dense(32,activation='relu'),
        Dense(26,activation='softmax')
    ]
)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [92]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy' , metrics=['accuracy'])

In [93]:
model.fit(x_train,y_train, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3456 - loss: 2.3359 - val_accuracy: 0.7322 - val_loss: 0.8965
Epoch 2/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7718 - loss: 0.7604 - val_accuracy: 0.8081 - val_loss: 0.6262
Epoch 3/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8383 - loss: 0.5511 - val_accuracy: 0.8525 - val_loss: 0.5275
Epoch 4/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8740 - loss: 0.4390 - val_accuracy: 0.8656 - val_loss: 0.4301
Epoch 5/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8927 - loss: 0.3651 - val_accuracy: 0.8741 - val_loss: 0.3892
Epoch 6/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9096 - loss: 0.3026 - val_accuracy: 0.8922 - val_loss: 0.3381
Epoch 7/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9197 - loss: 0.2600 - val_accuracy: 0.9062 - val_loss: 0.2981
Epoch 8/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9282 - loss: 0.2329 - val_accuracy: 0.9097 - val_loss: 0.2929
Epoch 9/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9336 - loss: 0.2075 - val_accuracy: 0.9094 - val_loss: 0.2627
Epoch 10/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9372 - loss: 0.1934 - val_accuracy: 0.9116 - val_loss: 0.2701
Epoch 11/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9461 - loss: 0.1719 - val_accuracy: 0.9275 - val_loss: 0.2246
Epoch 12/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9553 - loss: 0.1494 - val_accuracy: 0.9278 - val_loss: 0.2177
Epoch 13/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9558 - loss: 0.1388 - val_accuracy: 0.9241 - val_loss: 0.2235
Epoch 14/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9578 - loss: 0.1290 - val_accuracy: 0.9284 - val_loss: 0.2117
Epoch 15/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9628 - loss: 0.1214 - val_accuracy: 0.9275 - val_loss: 0.2077
Epoch 16/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9636 - loss: 0.1224 - val_accuracy: 0.9359 - val_loss: 0.1949
Epoch 17/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9645 - loss: 0.1096 - val_accuracy: 0.9353 - val_loss: 0.2004
Epoch 18/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9688 - loss: 0.0995 - val_accuracy: 0.9300 - val_loss: 0.2052
Epoch 19/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9746 - loss: 0.0867 - val_accuracy: 0.9416 - val_loss: 0.1847
Epoch 20/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9686 - loss: 0.0925 - val_accuracy: 0.9400 - val_loss: 0.1786

In [94]:
predictions = model.predict(x_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [98]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'\n✅ Test Accuracy: {accuracy:.2f}')

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9328 - loss: 0.2163

✅ Test Accuracy: 0.94

In [99]:
predicted_labels = encoder_labels.inverse_transform(np.argmax(predictions,axis=1))

actual_labels = encoder_labels.inverse_transform(y_test)

In [100]:
# Print some predicted and actual results
print("Some Predicted and Actual Results:")
for i in range(10):
    print("Predicted:", predicted_labels[i], "Actual:", actual_labels[i])

Some Predicted and Actual Results:
Predicted: X Actual: X
Predicted: R Actual: R
Predicted: P Actual: P
Predicted: I Actual: I
Predicted: I Actual: I
Predicted: Z Actual: Z
Predicted: C Actual: C
Predicted: Y Actual: Y
Predicted: G Actual: G
Predicted: X Actual: X