In [4]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('house.csv')
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [7]:
df.shape

(506, 14)

In [8]:
df.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [9]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [11]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [14]:
x = df.drop(columns=['MEDV'])
y = df['MEDV']

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x ,y ,test_size=0.2, random_state=42)

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential(
    [
        Dense(128, input_dim = x_train_scaled.shape[1], activation='relu'),
        Dense(64,activation='relu'),
        Dense(32,activation='relu'),
        Dense(16,activation='relu'),
        Dense(1,activation='linear')
    ]
)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [36]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

In [37]:
model.fit(x_train_scaled, y_train, validation_split=0.2, epochs=10, verbose=1)

Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 6.2851 - mae: 1.9061 - val_loss: 11.6034 - val_mae: 2.5045
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5300 - mae: 1.8899 - val_loss: 11.6763 - val_mae: 2.4746
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2653 - mae: 1.6870 - val_loss: 13.1454 - val_mae: 2.6383
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.0992 - mae: 1.7658 - val_loss: 11.8241 - val_mae: 2.5366
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.2735 - mae: 1.7565 - val_loss: 12.6575 - val_mae: 2.6261
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.9181 - mae: 1.7094 - val_loss: 10.6591 - val_mae: 2.4159
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.6092 - mae: 1.6561 - val_loss: 11.6214 - val_mae: 2.4873
Epoch 8/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3579 - mae: 1.7320 - val_loss: 11.2889 - val_mae: 2.4720
Epoch 9/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3366 - mae: 1.7432 - val_loss: 12.4189 - val_mae: 2.6050
Epoch 10/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.3907 - mae: 1.6256 - val_loss: 12.0426 - val_mae: 2.5442

In [39]:
#  Evaluate the model
loss, mae = model.evaluate(x_test_scaled, y_test)
print("Mean Absolute Error on test set:", mae)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 8.9840 - mae: 2.0844
Mean Absolute Error on test set: 2.275568723678589

In [40]:
#  Make predictions
predictions = model.predict(x_test_scaled)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

In [42]:
# Compare predicted and actual values
for i in range(10):
    print(f"Predicted Price: {predictions[i][0]:.2f} | Actual Price: {y_test.values[i]:.2f}")

Predicted Price: 27.73 | Actual Price: 23.60
Predicted Price: 34.83 | Actual Price: 32.40
Predicted Price: 16.78 | Actual Price: 13.60
Predicted Price: 24.35 | Actual Price: 22.80
Predicted Price: 16.26 | Actual Price: 16.10
Predicted Price: 19.98 | Actual Price: 20.00
Predicted Price: 17.71 | Actual Price: 17.80
Predicted Price: 14.73 | Actual Price: 14.00
Predicted Price: 25.81 | Actual Price: 19.60
Predicted Price: 19.10 | Actual Price: 16.80